### ISSUE TITLE
SonarQube 9.x compatibility

### ISSUE THREAD

**Issue by arthepsy** [SonarOpenCommunity/sonar-cxx#2241]
Latest release doesn't seem to work on latest SonarQube (9.0.1):
```
java.lang.NoSuchMethodError: 'org.sonar.api.server.rule.RulesDefinition$NewRule org.sonar.api.server.rule.RulesDefinition$NewRule.setEffortToFixDescription(java.lang.String)'
        at org.sonar.cxx.squidbridge.annotations.AnnotationBasedRulesDefinition.setupSqaleModel(AnnotationBasedRulesDefinition.java:184)
        at org.sonar.cxx.squidbridge.annotations.AnnotationBasedRulesDefinition.addRuleClasses(AnnotationBasedRulesDefinition.java:102)
        at org.sonar.cxx.squidbridge.annotations.AnnotationBasedRulesDefinition.addRuleClasses(AnnotationBasedRulesDefinition.java:88)
        at org.sonar.plugins.cxx.CxxRuleRepository.define(CxxRuleRepository.java:34)
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53)
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:117)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:49)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:87)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)                                                                                                                                                  at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:84)
        at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)                                                                                                                                 at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)                                                                                                                                             at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by guwirth** [comment]
Hi @arthepsy,

please have a look to #2229.

Regards,

**Comment by guwirth** [comment]
API changes: https://docs.sonarqube.org/latest/extend/developing-plugin/#header-4

**Comment by guwirth** [comment]
Hi @arthepsy,

we have a first version running on 9.x. Can you test it please and give us feedback:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/builds/41426760/artifacts

Regards

**Comment by guwirth** [comment]
Hi @Andylau1994,

we have a first version running on 9.x. Can you test it please and give us feedback:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/builds/41426760/artifacts

Regards

**Comment by guwirth** [comment]
Hi @lg2de,

we have a first version running on 9.x. Can you test it please and give us feedback:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/builds/41426760/artifacts

Regards

**Comment by guwirth** [comment]
Use this version for testing: https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.1.x-beta

**Comment by guwirth** [comment]
Use this version for testing: https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.1.x-beta1

**Comment by lg2de** [comment]
I've installed the mentioned beta, even the version number is still 2.0.x ;).
We are currently running 9.0.1, I'll update to 9.2.x soon and start detailed testing.
So far it looks good. Thanks!

**Comment by DJViking** [comment]
Tried the latest 2.1.0-beta1 on SonarQube 9.2.4.
I placed the JARs in SonarQube extensions/plugin directory.
SonarQube will not start with this plugin.

```
2022.01.24 14:36:49 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.NullPointerException: Plugin key is missing from manifest
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at org.sonar.core.platform.PluginInfo.<init>(PluginInfo.java:104)
        at org.sonar.server.plugins.ServerPluginInfo.<init>(ServerPluginInfo.java:32)
        at org.sonar.server.plugins.ServerPluginInfo.create(ServerPluginInfo.java:38)
        at org.sonar.server.plugins.PluginJarLoader.lambda$getExternalPluginsMetadata$5(PluginJarLoader.java:205)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.sonar.server.plugins.PluginJarLoader.loadPluginsFromDir(PluginJarLoader.java:235)
        at org.sonar.server.plugins.PluginJarLoader.getExternalPluginsMetadata(PluginJarLoader.java:205)
        at org.sonar.server.plugins.PluginJarLoader.loadPlugins(PluginJarLoader.java:91)
        at org.sonar.server.plugins.ServerPluginManager.start(ServerPluginManager.java:64)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:111)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
        at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:179)
        at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:87)
        at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pk1057** [comment]
> Tried the latest 2.1.0-beta1 on SonarQube 9.2.4. I placed the JARs in SonarQube extensions/plugin directory. SonarQube will not start with this plugin.
> 
> ```
> 2022.01.24 14:36:49 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
> java.lang.NullPointerException: Plugin key is missing from manifest
>         at java.base/java.util.Objects.requireNonNull(Objects.java:246)

I have the same problem :(

Is there a newer test build of the 2.1 plugin ?

**Comment by guwirth** [comment]
Hi @pk1057,

thanks for your feedback!

Sorry can't say too much. This beta version was tested with SonarQube 9.1.0.47736 only. Maybe there are new incompatible changes with SQ 9.2? On the main line we are supporting LTS versions only (7.9 & 8.9).

Regards,

**Comment by yachoor** [comment]
@pk1057 that issue is caused by placing non-plugin jar in extensions/plugin directory - for example the cxx-sslr-toolkit-2.0.6.2921.jar, which is a separate tool, not a sonar plugin

**Comment by guwirth** [comment]
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Install-the-Plugin

…
**Additional tools:**

cxx-sslr-toolkit-x.y.z.jar: is an additional tool to create an AST from parsed source code. The tool is useful to create XPath checks and to verify if the plugin can parse the source code.

**cxx-sslr-toolkit-x.y.z.jar is not a plugin. Do not copy it to the plugins folder.**

**Comment by pk1057** [comment]
> @pk1057 that issue is caused by placing non-plugin jar in extensions/plugin directory - for example the cxx-sslr-toolkit-2.0.6.2921.jar, which is a separate tool, not a sonar plugin

OK,
you are right, i had the cxx-slr-toolkit als in the plugin folder. 
Now it is starting properly.

Thank you !
